### ISSUE TITLE
ESP32 fails to control server

### ISSUE THREAD

**Issue by pascalboehler** [BHH-IT-Jahrgang2022/challenge1ICETruckLowLevelGroup#19]
The ESP32 script controls the fan when given servo commands and executing the servoFunction. No call of fan (setledc) is made.

Maybe hardware related.

**Comment by n3rdybyn4tur3** [comment]
after checking pins and cables and adjusting pinout numbers it's working now

**Comment by pascalboehler** [comment]
fixed.
